[project]
name = "hashlock-lending"
description = "HashLock Lending â€” Trustless BTCFi lending on Stacks"
clarity_version = 4
cache_dir = "./.clarinet-cache"

[contracts.hashlock-core]
path = "contracts/hashlock-core.clar"
clarity_version = 4

[contracts.hashlock-isolated-sbtc-v1]
path = "contracts/hashlock-isolated-sbtc-v1.clar"
clarity_version = 4

[contracts.flash-receiver-example]
path = "contracts/flash-receiver-example.clar"
clarity_version = 4
